### ISSUE TITLE
MSVCR110D.dll is missing from your computer

### ISSUE THREAD

**Issue by hellochar** [benkuper/MyOSC#2]
Hey benkuper, just tried running this by downloading the Windows installer on 64-bit Windows 8.1. Installing was fine but when I start the application there's an error window saying "The program can't start because MSVCR110D.dll is missing from your computer." Should this file be added into the installer?

**Comment by InnocentlyVoid** [comment]
I'm glad I'm not the only one having this issue. Though it's the strangest thing. On my desktop it works fine, but on my laptop it get's this error and i can't seem to get around it as much as I replace the file or  re-install Visual Studio. any idea's?

**Comment by ghost** [comment]
Having the same issue

**Comment by benkuper** [comment]
Sorry for this very late answer, i updated MyOS.exe with the missing dll
If there is still the problem, try downloading msvcr110d.dll and msvcp110d.dll (for x86, even if you have a x64 system) and add it to the MyOSC installation folder, next to the MyOSC.exe

**Comment by JaydeepDahiya** [comment]
Download and install Microsoft Visual C++ Redistributable 2012 x86 version (even if your laptop is x64)

http://www.microsoft.com/en-us/download/details.aspx?id=30679#

**Comment by benkuper** [comment]
Last version of Myo Extension is compiled in Release mode, this dependency should not be a problem now.

**Comment by zhukovgreen** [comment]
@JaydeepDahiya Thank you. It was the issue in my case.
