### ISSUE TITLE
EMG-data

### ISSUE THREAD

**Issue by sarahlisette** [benkuper/MyOSC#3]
Hi bankuper,
thanks a lot for this great tool! I'm wondering wether there is a way to also access raw EMG-data through your application?

**Comment by benkuper** [comment]
Hi sarah,
i just updated the Windows version MyOSC to SDK 0.8.1.
There is now support for EMG data streaming and disabling myo auto lock

**Comment by benkuper** [comment]
Hi, i also updated the OSX version.
Cheers !

**Comment by sarahlisette** [comment]
Great, thank you so much :-)

2015-04-28 14:41 GMT-04:00 Ben Kuper notifications@github.com:

> Closed #3 https://github.com/benkuper/MyOSC/issues/3.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/benkuper/MyOSC/issues/3#event-292291117.

## 

Sarah Platte | Research Assistant | Opera of the Future

MIT Media Lab
School of Architecture + Planning
Massachusetts Institute of Technology
